[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10

opacity = 0.85

option_as_alt = "Both"

startup_mode = "Maximized"

[font]
size = 15

[[keyboard.bindings]]
key = "3"
mods = "Alt"
chars = "#"

[[keyboard.bindings]]
key = "0"
mods = "Alt"
mode = "AppCursor"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "9"
mods = "Alt"
mode = "AppCursor"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "8"
mods = "Alt"
mode = "AppCursor"
action = "ResetFontSize"
